config/routes.rb
Admin::Application.routes.draw do
  devise_for :users
  root 'parents#index'
  resources :parents
  resources :kids
  resources :recipients
  resources :albums, only: [:index]
  resources :scheduled_emails, only: [:index]
  resources :sendgrid, only: [:index, :create]
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :kid
end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :user
  belongs_to :kid, :class_name => "User"
end

app/models/delivery.rb
class Delivery < User
  # STI User
end

app/models/kid.rb
class Kid < User
  has_many :inverse_chidren, :class_name => "Child", :foreign_key => "child_id"
  has_many :parents, :through => :inverse_chidren, :source => :user
  
  has_one :album
  accepts_nested_attributes_for :album, allow_destroy: true, reject_if: lambda {|attributes| attributes['smugmug_id'].blank?}
end

app/models/mailing_address.rb
class MailingAddress < Address

end

app/models/mobile_phone.rb
class MobilePhone < Phone
end

app/models/parent.rb
class Parent < User
  REMINDER_DELIVERY_PREFERENCES =
    Map.new \
      :email_only    => 1,
      :sms_only      => 2,
      :email_and_sms => 3

  Fattr( :default_user_mailer_klass ){ UserMailer }
  fattr( :user_mailer_klass ){ self.class.default_user_mailer_klass }

  Fattr( :default_user_sms_notifier_klass ){ UserSmsNotifier }
  fattr( :user_sms_notifier_klass ){ self.class.default_user_sms_notifier_klass }

  has_many :recipients, :foreign_key => "user_id"
  has_many :deliveries, :through => :recipients, :source => :delivery
  has_many :children, :foreign_key => "user_id"
  has_many :kids, :through => :children, :source => :kid
  accepts_nested_attributes_for :kids, allow_destroy: true, reject_if: lambda {|attributes| attributes['name'].blank?}
  accepts_nested_attributes_for :deliveries, allow_destroy: true, reject_if: lambda {|attributes| attributes['email'].blank?}

  def deliver(kid, image_url, caption)
    self.deliveries.each do |delivery|
      puts "sending email to #{delivery.email} id=#{delivery.id}"
      ret = user_mailer_klass.daily_mail(delivery, self, kid, image_url, caption).deliver
      puts ret.inspect
    end
  end

  def send_upload_email_reminder
    user_mailer_klass.upload_reminder( self ).deliver
  end

  def send_upload_reminder
    case reminder_delivery_preference
    when REMINDER_DELIVERY_PREFERENCES.email_only
      send_upload_email_reminder
    when REMINDER_DELIVERY_PREFERENCES.sms_only
      send_upload_sms_reminder
    when REMINDER_DELIVERY_PREFERENCES.email_and_sms
      send_upload_email_reminder
      send_upload_sms_reminder
    else
      # do nothing
    end
  end

  def send_upload_sms_reminder
    user_sms_notifier_klass.new.upload_reminder self
  end

  def upload(filename, content, caption)
    smug_mug = SmugMug.new
    self.kids.each do |kid|
      ret = smug_mug.put_resource(kid.album.smugmug_id, filename, content, caption) if kid.album.smugmug_id
      email_hash = {
        :parent_id => self.id,
        :kid_id => kid.id,
        :image_id => ret['Image']['id'],
        :image_key => ret['Image']['Key'],
        :caption => caption
      }
      ScheduledEmail.create email_hash
    end
  end
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :user
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :user
  belongs_to :delivery, :class_name => "User"
end

app/models/scheduled_email.rb
class ScheduledEmail < ActiveRecord::Base
  belongs_to :parent
  belongs_to :kid
end

app/models/user.rb
class User < ActiveRecord::Base  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_one :mobile_phone
  has_many :phones
  has_one :home_address
  has_one :mailing_address
  has_many :addresses
  
  before_create :normalize
  
  def type_setter=(type_name)
    self[:type]=type_name
  end
  
  private
  
  def normalize
    self.email = self.email.downcase if self.email
    self.name = self.name.titleize if self.name
    self.sex = self.sex.to_sex if self.sex
  end
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = SmugMugWrapper.new.get_albums
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:id, :key, :nice_name, :title, :url, :references)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]

  def index
    @kids = Kid.all
  end

  def show
  end

  def new
    @kid = Kid.new
    @kid.album = Album.new
  end

  def edit
    @kid.album = Album.new unless @kid.album
  end

  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render action: 'show', status: :created, location: @kid }
      else
        format.html { render action: 'new' }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to parents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kid
      @kid = Kid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kid_params
      params.require(:kid).permit(:name, :birthdate, :sex, :email, album_attributes: [:id, :smugmug_id, :custom_url, :password, :_destroy])
    end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  def index
    @parents = Parent.all
  end

  def show
  end

  def new
    @parent = Parent.new
    @parent.kids.build
    @parent.deliveries.build
  end

  def edit
    @parent.kids.build
    @parent.deliveries.build
  end

  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render action: 'show', status: :created, location: @parent }
      else
        format.html { render action: 'new' }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:name, :birthdate, :sex, :email, :cell_phone, :reminder_delivery_preference,
        kids_attributes: [:id, :type_setter, :name, :sex, :birthdate, :_destroy],
        deliveries_attributes: [:id, :type_setter, :email, :_destroy])
    end
end

app/controllers/scheduled_emails_controller.rb
class ScheduledEmailsController < ApplicationController
  
  def index
    @scheduled_emails = ScheduledEmail.paginate(:page => params[:page], :per_page => 20).order(:created_at => :desc)
  end

end

app/views/parents/_form.html.erb
<%= form_for @parent, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cell_phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cell_phone, :class => 'text_field' %>
      <span class="help-inline">
        Must be of the format +12345678900. Country code at the front, and no symbols other than leading +.
      </span>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reminder_delivery_preference, :class => 'control-label' %>
    <div class="controls">
      <%
        options =
          [
            [ 'None'        , 0 ],
            [ 'Email Only'  , 1 ],
            [ 'SMS Only'    , 2 ],
            [ 'Email & SMS' , 3 ]
          ]

        selected =
          ( f.object.reminder_delivery_preference or 0 )
      %>
      <%=
        f.select \
          :reminder_delivery_preference,
          options_for_select( options , selected ),
          :class => 'text_field'
      %>
    </div>
  </div>
  
  <div class="control-group">
	  Children:
	  <ul>
	    <%= f.fields_for :kids do |kids_form| %>
	      <li>
	      	<%= kids_form.hidden_field :type_setter, :value => 'Kid' %>
	      	
	        <%= kids_form.label :name %>
	        <%= kids_form.text_field :name %>
	 
	        <%= kids_form.label :birthdate %>
	        <%= kids_form.date_field :birthdate %>
	        
	        <%= kids_form.label :sex %>
	        <%= kids_form.text_field :sex %>
	        
	       	<% if kids_form.object.id %>
	        	<%= link_to 'Show', kid_path(kids_form.object) %>
	        <% end %>
	      </li>
	    <% end %>
	  </ul>
  </div>
  
  <div class="control-group">
	  Email Recipients:
	  <ul>
	    <%= f.fields_for :deliveries do |deliveries_form| %>
	      <li>
	      	<%= deliveries_form.hidden_field :type_setter, :value => 'Delivery' %>
	      	
	        <%= deliveries_form.label :email %>
	        <%= deliveries_form.text_field :email %>
	      </li>
	    <% end %>
	  </ul>
  </div>
  
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                parents_path, :class => 'btn' %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<%- model_class = Parent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/parents/index.html.erb
<%- model_class = Parent -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= link_to parent.id, parent_path(parent) %></td>
        <td><%= parent.name %></td>
        <td><%= parent.email %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_parent_path(parent), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      parent_path(parent),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_parent_path,
            :class => 'btn btn-primary' %>

app/views/parents/new.html.erb
<%- model_class = Parent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/parents/show.html.erb
<%- model_class = Parent -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @parent.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @parent.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              parents_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_parent_path(@parent), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              parent_path(@parent),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>